### Анализ игр NBA

Подготовил Григорий Крюков

Источник данных: https://www.kaggle.com/datasets/nathanlauga/nba-games

In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
from datetime import datetime

In [2]:
N = 30
df = pd.read_csv("games.csv")
df["date"] = [datetime.strptime(df.GAME_DATE_EST[i], "%Y-%m-%d") for i in range(len(df))]
df = df.sort_values('date')
df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,date
18433,2003-10-05,10300001,Final,1610612762,1610612742,2003,1610612762,90.0,0.457,0.735,...,41.0,1610612742,85.0,0.447,0.500,0.250,20.0,38.0,1,2003-10-05
18432,2003-10-06,10300002,Final,1610612763,1610612749,2003,1610612763,105.0,0.494,0.618,...,48.0,1610612749,94.0,0.427,0.700,0.154,20.0,43.0,1,2003-10-06
18425,2003-10-07,10300010,Final,1610612764,1610612752,2003,1610612764,104.0,0.506,0.677,...,45.0,1610612752,86.0,0.380,0.852,0.188,19.0,37.0,1,2003-10-07
18424,2003-10-07,10300006,Final,1610612747,1610612744,2003,1610612747,NaN,NaN,NaN,...,NaN,1610612744,NaN,NaN,NaN,NaN,NaN,NaN,0,2003-10-07
18427,2003-10-07,10300004,Final,1610612742,1610612753,2003,1610612742,99.0,0.488,0.667,...,52.0,1610612753,89.0,0.408,0.727,0.350,15.0,34.0,1,2003-10-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,2022-03-12,22101010,Final,1610612762,1610612758,2021,1610612762,134.0,0.558,0.710,...,44.0,1610612758,125.0,0.500,0.857,0.394,27.0,33.0,1,2022-03-12
4,2022-03-12,22101009,Final,1610612743,1610612761,2021,1610612743,115.0,0.551,0.750,...,39.0,1610612761,127.0,0.471,0.760,0.387,28.0,50.0,0,2022-03-12
3,2022-03-12,22101008,Final,1610612744,1610612749,2021,1610612744,122.0,0.484,0.933,...,55.0,1610612749,109.0,0.413,0.696,0.386,27.0,39.0,1,2022-03-12
1,2022-03-12,22101006,Final,1610612741,1610612739,2021,1610612741,101.0,0.443,0.933,...,46.0,1610612739,91.0,0.419,0.824,0.208,19.0,40.0,1,2022-03-12
0,2022-03-12,22101005,Final,1610612748,1610612750,2021,1610612748,104.0,0.398,0.760,...,53.0,1610612750,113.0,0.422,0.875,0.357,21.0,46.0,0,2022-03-12

In [3]:
moods = np.ones(N)
moods_h = np.zeros(len(df))
moods_v = np.zeros(len(df))
k = 1610612737
for i in range(len(df)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    moods_h[i] = moods[home]
    moods_v[i] = moods[visitor]
    if df.HOME_TEAM_WINS.iloc[i] == 1:
        moods[home] = 1
        moods[visitor] = 0
    else:
        moods[home] = 0
        moods[visitor] = 1
df['moods_h'] = moods_h
df['moods_v'] = moods_v
df['moods_diff'] = moods_h - moods_v
df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,date,moods_h,moods_v,moods_diff
18433,2003-10-05,10300001,Final,1610612762,1610612742,2003,1610612762,90.0,0.457,0.735,...,0.447,0.500,0.250,20.0,38.0,1,2003-10-05,1.0,1.0,0.0
18432,2003-10-06,10300002,Final,1610612763,1610612749,2003,1610612763,105.0,0.494,0.618,...,0.427,0.700,0.154,20.0,43.0,1,2003-10-06,1.0,1.0,0.0
18425,2003-10-07,10300010,Final,1610612764,1610612752,2003,1610612764,104.0,0.506,0.677,...,0.380,0.852,0.188,19.0,37.0,1,2003-10-07,1.0,1.0,0.0
18424,2003-10-07,10300006,Final,1610612747,1610612744,2003,1610612747,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,2003-10-07,1.0,1.0,0.0
18427,2003-10-07,10300004,Final,1610612742,1610612753,2003,1610612742,99.0,0.488,0.667,...,0.408,0.727,0.350,15.0,34.0,1,2003-10-07,0.0,1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,2022-03-12,22101010,Final,1610612762,1610612758,2021,1610612762,134.0,0.558,0.710,...,0.500,0.857,0.394,27.0,33.0,1,2022-03-12,0.0,0.0,0.0
4,2022-03-12,22101009,Final,1610612743,1610612761,2021,1610612743,115.0,0.551,0.750,...,0.471,0.760,0.387,28.0,50.0,0,2022-03-12,0.0,1.0,-1.0
3,2022-03-12,22101008,Final,1610612744,1610612749,2021,1610612744,122.0,0.484,0.933,...,0.413,0.696,0.386,27.0,39.0,1,2022-03-12,1.0,1.0,0.0
1,2022-03-12,22101006,Final,1610612741,1610612739,2021,1610612741,101.0,0.443,0.933,...,0.419,0.824,0.208,19.0,40.0,1,2022-03-12,1.0,0.0,1.0
0,2022-03-12,22101005,Final,1610612748,1610612750,2021,1610612748,104.0,0.398,0.760,...,0.422,0.875,0.357,21.0,46.0,0,2022-03-12,1.0,0.0,1.0

Сила команд

In [4]:
w = np.zeros(N)
prev_win = [1 for i in range(N)] # Выиграна ли предыдущая игра
A = [np.zeros((2, 2)) for i in range(N)] # Матрицы переходов
k = 1610612737 # Параметр, вычитание которого из id команды приводит к порядковому номеру
# Проходимся циклом с конца таблицы (в хронологическом порядке), заполняем соответствующие значения матриц переходов
for i in range(len(df)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    if df.HOME_TEAM_WINS.iloc[i] == 1:
        A[home][1 - prev_win[home]][0] += 1
        A[visitor][1 - prev_win[visitor]][1] += 1
        prev_win[home] = 1
        prev_win[visitor] = 0
    else:
        A[home][1 - prev_win[home]][1] += 1
        A[visitor][1 - prev_win[visitor]][0] += 1
        prev_win[home] = 0
        prev_win[visitor] = 1
        
# Теперь поделим число выигранных матчей на число всех матчей
for i in range(N):
    w[i] = A[i].sum(axis=1)[0] / A[i].sum()
    
w_base = w.copy()

In [5]:
w

array([0.46647399, 0.55733186, 0.5107832 , 0.45656081, 0.50495627,
       0.57126568, 0.55779183, 0.56203545, 0.56357388, 0.51618497,
       0.52044818, 0.56721311, 0.47755102, 0.4004884 , 0.44183314,
       0.40256567, 0.44791054, 0.52036718, 0.45147929, 0.51665693,
       0.49853372, 0.41005451, 0.64105379, 0.52561888, 0.51515152,
       0.53962704, 0.49853544, 0.43506494, 0.48242075, 0.40103159])

In [6]:
N = 30
prev_win = [1 for i in range(N)] # Выиграна ли предыдущая игра
TM = [np.zeros((2, 2)) for i in range(N)] # Матрицы переходов
k = 1610612737 # Параметр, вычитание которого из id команды приводит к порядковому номеру
# Проходимся циклом с конца таблицы (в хронологическом порядке), заполняем соответствующие значения матриц переходов
for i in range(len(df)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    if df.HOME_TEAM_WINS.iloc[i] == 1:
        TM[home][1 - prev_win[home]][0] += 1
        TM[visitor][1 - prev_win[visitor]][1] += 1
        prev_win[home] = 1
        prev_win[visitor] = 0
    else:
        TM[home][1 - prev_win[home]][1] += 1
        TM[visitor][1 - prev_win[visitor]][0] += 1
        prev_win[home] = 0
        prev_win[visitor] = 1
        
# Теперь нам осталось получить "настоящие" оценки матриц переходов
# Для этого все строки матриц TM нормируем так, чтобы сумма по строкам была равна 1
for i in range(N):
    TM[i][0] /= TM[i][0].sum()
    TM[i][1] /= TM[i][1].sum()
    
TM_base = TM.copy()

In [7]:
TM[11]

array([[0.57899807, 0.42100193],
       [0.55050505, 0.44949495]])

Сила команд по сезонам

In [8]:
df[df.SEASON == 2007]

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,date,moods_h,moods_v,moods_diff
12835,2007-10-06,10700001,Final,1610612738,1610612761,2007,1610612738,89.0,0.461,0.696,...,0.388,0.625,0.321,21.0,41.0,1,2007-10-06,0.0,0.0,0.0
12834,2007-10-08,10700006,Final,1610612765,1610612748,2007,1610612765,103.0,0.479,0.714,...,0.403,0.739,0.389,22.0,35.0,1,2007-10-08,0.0,0.0,0.0
12833,2007-10-08,10700005,Final,1610612753,1610612737,2007,1610612753,93.0,0.413,0.560,...,0.408,0.702,0.429,19.0,39.0,0,2007-10-08,0.0,1.0,-1.0
12827,2007-10-09,10700008,Final,1610612749,1610612741,2007,1610612749,93.0,0.417,0.651,...,0.485,0.600,0.500,24.0,38.0,1,2007-10-09,0.0,0.0,0.0
12826,2007-10-09,10700007,Final,1610612739,1610612764,2007,1610612739,62.0,0.306,0.800,...,0.354,0.690,0.357,17.0,42.0,0,2007-10-09,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11429,2008-06-08,40700402,Final,1610612738,1610612747,2007,1610612738,108.0,0.529,0.711,...,0.494,1.000,0.476,20.0,36.0,1,2008-06-08,1.0,0.0,1.0
11428,2008-06-10,40700403,Final,1610612747,1610612738,2007,1610612747,87.0,0.435,0.618,...,0.349,0.682,0.444,19.0,45.0,1,2008-06-10,0.0,1.0,-1.0
11427,2008-06-12,40700404,Final,1610612747,1610612738,2007,1610612747,91.0,0.416,0.724,...,0.452,0.821,0.364,15.0,40.0,0,2008-06-12,1.0,0.0,1.0
11426,2008-06-15,40700405,Final,1610612747,1610612738,2007,1610612747,103.0,0.456,0.742,...,0.429,0.774,0.364,20.0,37.0,1,2008-06-15,0.0,1.0,-1.0
11425,2008-06-17,40700406,Final,1610612738,1610612747,2007,1610612738,131.0,0.494,0.865,...,0.422,0.737,0.370,16.0,29.0,1,2008-06-17,0.0,1.0,-1.0

In [9]:
w_seasons = []
for s in range(2004, 2022):
    w = np.zeros(N)
    prev_win = [1 for i in range(N)] # Выиграна ли предыдущая игра
    A = [np.zeros((2, 2)) for i in range(N)] # Матрицы переходов
    k = 1610612737 # Параметр, вычитание которого из id команды приводит к порядковому номеру
    # Проходимся циклом с конца таблицы (в хронологическом порядке), заполняем соответствующие значения матриц переходов
    dt = df[df.SEASON == s]
    for i in range(len(dt)):
        home = dt.HOME_TEAM_ID.iloc[i] - k
        visitor = dt.VISITOR_TEAM_ID.iloc[i] - k
        if dt.HOME_TEAM_WINS.iloc[i] == 1:
            A[home][1 - prev_win[home]][0] += 1
            A[visitor][1 - prev_win[visitor]][1] += 1
            prev_win[home] = 1
            prev_win[visitor] = 0
        else:
            A[home][1 - prev_win[home]][1] += 1
            A[visitor][1 - prev_win[visitor]][0] += 1
            prev_win[home] = 0
            prev_win[visitor] = 1
        
    # Теперь поделим число выигранных матчей на число всех матчей
    for i in range(N):
        w[i] = A[i].sum(axis=1)[0] / A[i].sum()
        
    w_seasons.append(w)

In [10]:
w_seasons

[array([0.16666667, 0.54347826, 0.51190476, 0.22352941, 0.56043956,
        0.67676768, 0.60869565, 0.42352941, 0.6043956 , 0.44186047,
        0.43373494, 0.72      , 0.38095238, 0.53488372, 0.5       ,
        0.41860465, 0.46428571, 0.54      , 0.52222222, 0.75      ,
        0.3255814 , 0.58241758, 0.72222222, 0.625     , 0.41860465,
        0.3255814 , 0.53409091, 0.53684211, 0.64864865, 0.23529412]),
 array([0.33707865, 0.4       , 0.61165049, 0.46067416, 0.48958333,
        0.71681416, 0.55789474, 0.41573034, 0.46067416, 0.59405941,
        0.56701031, 0.63392857, 0.47368421, 0.42222222, 0.59405941,
        0.29213483, 0.46590909, 0.51041667, 0.47191011, 0.64545455,
        0.26666667, 0.52083333, 0.69902913, 0.42696629, 0.34831461,
        0.48314607, 0.59139785, 0.5       , 0.73148148, 0.32222222]),
 array([0.38888889, 0.31111111, 0.58715596, 0.46067416, 0.62      ,
        0.76041667, 0.54255319, 0.53535354, 0.63541667, 0.51136364,
        0.50526316, 0.50537634, 0.35555556, 0.42222222, 0.5       ,
        0.42045455, 0.5       , 0.43333333, 0.42528736, 0.70707071,
        0.38888889, 0.43333333, 0.71028037, 0.4       , 0.58947368,
        0.60747664, 0.28888889, 0.4893617 , 0.6509434 , 0.4       ]),
 array([0.49484536, 0.74782609, 0.53465347, 0.66336634, 0.41573034,
        0.61052632, 0.59139785, 0.59770115, 0.64516129, 0.31460674,
        0.67889908, 0.16853933, 0.33707865, 0.26136364, 0.43181818,
        0.30232558, 0.64285714, 0.46067416, 0.4787234 , 0.65957447,
        0.52272727, 0.47191011, 0.66346154, 0.23595506, 0.5       ,
        0.64356436, 0.31034483, 0.5212766 , 0.69158879, 0.38202247]),
 array([0.56435644, 0.73076923, 0.76923077, 0.61702128, 0.50515464,
        0.6       , 0.67619048, 0.37931034, 0.64705882, 0.25842697,
        0.76785714, 0.51041667, 0.4       , 0.34444444, 0.42696629,
        0.39325843, 0.69642857, 0.44444444, 0.50526316, 0.56666667,
        0.64210526, 0.2       , 0.62765957, 0.26966292, 0.40449438,
        0.57446809, 0.28888889, 0.24719101, 0.4893617 , 0.4       ]),
 array([0.63      , 0.63157895, 0.71      , 0.43333333, 0.51578947,
        0.66315789, 0.62105263, 0.33333333, 0.52222222, 0.38202247,
        0.69911504, 0.54255319, 0.54639175, 0.21111111, 0.15730337,
        0.38636364, 0.75      , 0.40449438, 0.36666667, 0.64761905,
        0.59375   , 0.31460674, 0.59183673, 0.57894737, 0.46666667,
        0.63636364, 0.48888889, 0.33333333, 0.34444444, 0.5       ]),
 array([0.52475248, 0.6969697 , 0.28089888, 0.52083333, 0.71698113,
        0.69369369, 0.6       , 0.43333333, 0.52222222, 0.36666667,
        0.66666667, 0.68807339, 0.42222222, 0.26666667, 0.30337079,
        0.48387097, 0.65263158, 0.44680851, 0.4787234 , 0.46666667,
        0.56842105, 0.31460674, 0.71276596, 0.64761905, 0.3       ,
        0.52222222, 0.59803922, 0.30337079, 0.36666667, 0.42222222]),
 array([0.59459459, 0.60227273, 0.33823529, 0.35294118, 0.74324324,
        0.51388889, 0.58666667, 0.36764706, 0.51470588, 0.59493671,
        0.5875    , 0.69230769, 0.47058824, 0.42647059, 0.33823529,
        0.54794521, 0.54794521, 0.62025316, 0.55555556, 0.5       ,
        0.44117647, 0.33823529, 0.75609756, 0.71590909, 0.33823529,
        0.52777778, 0.6       , 0.29411765, 0.38235294, 0.13235294]),
 array([0.52631579, 0.49462366, 0.30681818, 0.35555556, 0.55445545,
        0.5       , 0.66315789, 0.58415842, 0.55789474, 0.66666667,
        0.4893617 , 0.76106195, 0.44680851, 0.39772727, 0.58947368,
        0.64      , 0.25555556, 0.60747664, 0.4494382 , 0.33707865,
        0.41573034, 0.38202247, 0.70642202, 0.7       , 0.44318182,
        0.54444444, 0.65384615, 0.36666667, 0.37777778, 0.24444444]),
 array([0.44791667, 0.31111111, 0.41111111, 0.45555556, 0.61052632,
        0.58762887, 0.43820225, 0.60416667, 0.66315789, 0.66990291,
        0.34444444, 0.66363636, 0.19318182, 0.51136364, 0.54455446,
        0.43820225, 0.28888889, 0.64220183, 0.22727273, 0.59090909,
        0.65      , 0.38202247, 0.72072072, 0.68224299, 0.60416667,
        0.28888889, 0.59375   , 0.53      , 0.37078652, 0.5212766 ]),
 array([0.6952381 , 0.4893617 , 0.66666667, 0.5483871 , 0.59803922,
        0.58947368, 0.36666667, 0.8018018 , 0.6728972 , 0.63461538,
        0.27777778, 0.45555556, 0.49473684, 0.24719101, 0.47311828,
        0.23595506, 0.3258427 , 0.47191011, 0.23333333, 0.5       ,
        0.60215054, 0.35227273, 0.63829787, 0.52808989, 0.60215054,
        0.48888889, 0.64      , 0.56565657, 0.41573034, 0.41111111]),
 array([0.57575758, 0.59139785, 0.67272727, 0.38202247, 0.51111111,
        0.46808511, 0.42696629, 0.81415929, 0.48421053, 0.62765957,
        0.21348315, 0.57692308, 0.40909091, 0.34831461, 0.27586207,
        0.4137931 , 0.46067416, 0.5625    , 0.14606742, 0.30681818,
        0.53      , 0.44318182, 0.7755102 , 0.67619048, 0.66055046,
        0.49438202, 0.52173913, 0.5       , 0.5106383 , 0.60824742]),
 array([0.53684211, 0.63551402, 0.63207547, 0.39772727, 0.49473684,
        0.39325843, 0.48888889, 0.83962264, 0.66666667, 0.61052632,
        0.32222222, 0.5       , 0.5106383 , 0.41573034, 0.25      ,
        0.39772727, 0.34831461, 0.5       , 0.34831461, 0.32954545,
        0.48913043, 0.40229885, 0.71153846, 0.56043956, 0.60204082,
        0.60204082, 0.53191489, 0.59803922, 0.46590909, 0.4494382 ]),
 array([0.31034483, 0.67619048, 0.58715596, 0.57894737, 0.35227273,
        0.32954545, 0.57471264, 0.71028037, 0.77669903, 0.51724138,
        0.42045455, 0.52688172, 0.52688172, 0.56666667, 0.37209302,
        0.33333333, 0.31818182, 0.58695652, 0.6185567 , 0.25581395,
        0.59340659, 0.31818182, 0.56521739, 0.58241758, 0.69072165,
        0.59375   , 0.29885057, 0.5326087 , 0.47126437, 0.43678161]),
 array([0.36781609, 0.58947368, 0.25581395, 0.3908046 , 0.28735632,
        0.41176471, 0.65      , 0.66972477, 0.64948454, 0.59340659,
        0.46590909, 0.48863636, 0.73267327, 0.43678161, 0.50549451,
        0.24137931, 0.49450549, 0.56666667, 0.62886598, 0.24418605,
        0.63106796, 0.47126437, 0.58510638, 0.59340659, 0.7       ,
        0.61111111, 0.40229885, 0.41860465, 0.48351648, 0.50574713]),
 array([0.30555556, 0.66666667, 0.29411765, 0.4875    , 0.34285714,
        0.56179775, 0.61616162, 0.25714286, 0.59782609, 0.64835165,
        0.72277228, 0.62745098, 0.75824176, 0.30882353, 0.47560976,
        0.31428571, 0.44827586, 0.60714286, 0.57142857, 0.475     ,
        0.44827586, 0.43037975, 0.4556962 , 0.61176471, 0.72222222,
        0.58139535, 0.4625    , 0.34177215, 0.33802817, 0.34285714]),
 array([0.58163265, 0.46987952, 0.32467532, 0.46753247, 0.43589744,
        0.58536585, 0.625     , 0.5443038 , 0.28205128, 0.61052632,
        0.60240964, 0.53164557, 0.64      , 0.33766234, 0.65934066,
        0.56626506, 0.31578947, 0.48101266, 0.69318182, 0.67326733,
        0.56097561, 0.4556962 , 0.44871795, 0.31168831, 0.38961039,
        0.71590909, 0.54117647, 0.45783133, 0.30769231, 0.4556962 ]),
 array([0.48571429, 0.59722222, 0.56944444, 0.4084507 , 0.63380282,
        0.63380282, 0.57534247, 0.69863014, 0.26760563, 0.50684932,
        0.40277778, 0.68      , 0.60273973, 0.57534247, 0.52112676,
        0.46478873, 0.26388889, 0.34722222, 0.62318841, 0.8028169 ,
        0.37142857, 0.39726027, 0.4109589 , 0.31428571, 0.55555556,
        0.61971831, 0.66216216, 0.42857143, 0.29577465, 0.47222222])]

In [11]:
TM_seasons = []
for s in range(2004, 2022):
    w = np.zeros(N)
    prev_win = [1 for i in range(N)] # Выиграна ли предыдущая игра
    A = [np.zeros((2, 2)) for i in range(N)] # Матрицы переходов
    k = 1610612737 # Параметр, вычитание которого из id команды приводит к порядковому номеру
    # Проходимся циклом с конца таблицы (в хронологическом порядке), заполняем соответствующие значения матриц переходов
    dt = df[df.SEASON == s]
    for i in range(len(dt)):
        home = dt.HOME_TEAM_ID.iloc[i] - k
        visitor = dt.VISITOR_TEAM_ID.iloc[i] - k
        if dt.HOME_TEAM_WINS.iloc[i] == 1:
            A[home][1 - prev_win[home]][0] += 1
            A[visitor][1 - prev_win[visitor]][1] += 1
            prev_win[home] = 1
            prev_win[visitor] = 0
        else:
            A[home][1 - prev_win[home]][1] += 1
            A[visitor][1 - prev_win[visitor]][0] += 1
            prev_win[home] = 0
            prev_win[visitor] = 1
            
    # Теперь нам осталось получить "настоящие" оценки матриц переходов
    # Для этого все строки матриц TM нормируем так, чтобы сумма по строкам была равна 1
    for i in range(N):
        A[i][0] /= A[i][0].sum()
        A[i][1] /= A[i][1].sum()
    TM_seasons.append(A)

In [12]:
TM_seasons[0][29]

array([[0.2       , 0.8       ],
       [0.24615385, 0.75384615]])

Стандартная модель

In [13]:
y_true = np.array(df.HOME_TEAM_WINS)

In [14]:
k = 1610612737
y_pred = np.zeros(len(df))
for i in range(len(df)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    if w_base[home] > w_base[visitor]:
        y_pred[i] = 1

In [15]:
np.abs(y_pred - y_true).mean()

0.436501783222205

In [16]:
k = 1610612737
y_pred = np.zeros(len(df))
for i in range(len(df)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    w_h = TM[home][int(df.moods_h.iloc[i])][0]
    w_v = TM[visitor][int(df.moods_v.iloc[i])][0]
    if w_h > w_v:
        y_pred[i] = 1

In [17]:
np.abs(y_pred - y_true).mean()

0.4730966041246705

Продвинутая модель.

In [21]:
data = df[df.SEASON > 2006]
y_true = np.array(data.HOME_TEAM_WINS)
data

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,date,moods_h,moods_v,moods_diff
12835,2007-10-06,10700001,Final,1610612738,1610612761,2007,1610612738,89.0,0.461,0.696,...,0.388,0.625,0.321,21.0,41.0,1,2007-10-06,0.0,0.0,0.0
12834,2007-10-08,10700006,Final,1610612765,1610612748,2007,1610612765,103.0,0.479,0.714,...,0.403,0.739,0.389,22.0,35.0,1,2007-10-08,0.0,0.0,0.0
12833,2007-10-08,10700005,Final,1610612753,1610612737,2007,1610612753,93.0,0.413,0.560,...,0.408,0.702,0.429,19.0,39.0,0,2007-10-08,0.0,1.0,-1.0
12827,2007-10-09,10700008,Final,1610612749,1610612741,2007,1610612749,93.0,0.417,0.651,...,0.485,0.600,0.500,24.0,38.0,1,2007-10-09,0.0,0.0,0.0
12826,2007-10-09,10700007,Final,1610612739,1610612764,2007,1610612739,62.0,0.306,0.800,...,0.354,0.690,0.357,17.0,42.0,0,2007-10-09,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,2022-03-12,22101010,Final,1610612762,1610612758,2021,1610612762,134.0,0.558,0.710,...,0.500,0.857,0.394,27.0,33.0,1,2022-03-12,0.0,0.0,0.0
4,2022-03-12,22101009,Final,1610612743,1610612761,2021,1610612743,115.0,0.551,0.750,...,0.471,0.760,0.387,28.0,50.0,0,2022-03-12,0.0,1.0,-1.0
3,2022-03-12,22101008,Final,1610612744,1610612749,2021,1610612744,122.0,0.484,0.933,...,0.413,0.696,0.386,27.0,39.0,1,2022-03-12,1.0,1.0,0.0
1,2022-03-12,22101006,Final,1610612741,1610612739,2021,1610612741,101.0,0.443,0.933,...,0.419,0.824,0.208,19.0,40.0,1,2022-03-12,1.0,0.0,1.0
0,2022-03-12,22101005,Final,1610612748,1610612750,2021,1610612748,104.0,0.398,0.760,...,0.422,0.875,0.357,21.0,46.0,0,2022-03-12,1.0,0.0,1.0

In [47]:
k = 1610612737
y_pred = np.zeros(len(data))
for i in range(len(data)):
    home = data.HOME_TEAM_ID.iloc[i] - k
    visitor = data.VISITOR_TEAM_ID.iloc[i] - k
    year = data.SEASON.iloc[i] - 2005
    if w_seasons[year][home] > w_seasons[year][visitor]:
        y_pred[i] = 1

In [48]:
np.abs(y_pred - y_true).mean()

0.4018219625705515

In [55]:
k = 1610612737
y_pred = np.zeros(len(data))
for i in range(len(data)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    year = data.SEASON.iloc[i] - 2005
    w_h = TM_seasons[year][home][int(df.moods_h.iloc[i])][0]
    w_v = TM_seasons[year][visitor][int(df.moods_v.iloc[i])][0]
    if w_h > w_v:
        y_pred[i] = 1

In [56]:
np.abs(y_pred - y_true).mean()

0.4983661748687989